/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Forms.RoundedPanel;
import com.mycompany.dictionary.ArbolB;
import com.mycompany.dictionary.ArbolBinarioBusqueda;
import com.mycompany.dictionary.ArbolMViasBusqueda;
import com.mycompany.dictionary.ArbolesAVL;
import com.mycompany.dictionary.IArbolBusqueda;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author user
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form FormDictionary
     */
    //IArbolBusqueda<String,String> arbolPrueba= new ArbolBinarioBusqueda<>();
    private IArbolBusqueda<String, String> arbolPrueba;
        

    public Splash() {
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jPanel3 = new RoundedPanel(40);
        mVias = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        binario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        binario1 = new javax.swing.JLabel();
        mVias1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBounds(230,10,100,150);
        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mVias.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mVias.setForeground(new java.awt.Color(255, 255, 255));
        mVias.setText("      ARBOL B");
        mVias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mVias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mViasMouseClicked(evt);
            }
        });
        jPanel3.add(mVias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 140, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 33, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Todos los derechos reservados 2023");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 214, 46));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DICCIONARIO INGLÉS-ESPAÑOL");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 238, 287, 88));

        binario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        binario.setForeground(new java.awt.Color(255, 255, 255));
        binario.setText("     ARBOL AVL");
        binario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        binario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binarioMouseClicked(evt);
            }
        });
        jPanel3.add(binario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Click en cualquier parte de aqui para empezar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 306, 290, 110));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        binario1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        binario1.setForeground(new java.awt.Color(255, 255, 255));
        binario1.setText("ARBOL BINARIO");
        binario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        binario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binario1MouseClicked(evt);
            }
        });
        jPanel3.add(binario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 40));

        mVias1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mVias1.setForeground(new java.awt.Color(255, 255, 255));
        mVias1.setText("ARBOL M-VIAS");
        mVias1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mVias1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVias1MouseClicked(evt);
            }
        });
        jPanel3.add(mVias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 40));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 480));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void mViasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mViasMouseClicked
        // TODO add your handling code here:
        arbolPrueba = new ArbolB<>(4);
        BaseDeDatos base = new BaseDeDatos(arbolPrueba);

        showMessageDialog(null, "Arbol B creado: Operacion exitosa ");
    }//GEN-LAST:event_mViasMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void binarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binarioMouseClicked
        // TODO add your handling code here:
        arbolPrueba=new ArbolesAVL<>();

            BaseDeDatos base= new BaseDeDatos(arbolPrueba);

        
        showMessageDialog(null, "Arbol AVL creado: Operacion exitosa ");
    }//GEN-LAST:event_binarioMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(arbolPrueba==null){
        showMessageDialog(null, "Por favor seleccione un arbol primero");
        }else{
        JFrame home= new Home(arbolPrueba);
        home.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void binario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binario1MouseClicked
        // TODO add your handling code here:
        arbolPrueba=new ArbolBinarioBusqueda<>();
        BaseDeDatos base= new BaseDeDatos(arbolPrueba);
        showMessageDialog(null, "Arbol Binario creado: Operacion exitosa ");
        
    }//GEN-LAST:event_binario1MouseClicked

    private void mVias1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVias1MouseClicked
        // TODO add your handling code here:
        arbolPrueba=new ArbolMViasBusqueda<>(4);
        BaseDeDatos base= new BaseDeDatos(arbolPrueba);
        showMessageDialog(null, "Arbol M-Vias creado: Operacion exitosa ");
    }//GEN-LAST:event_mVias1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel binario;
    private javax.swing.JLabel binario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mVias;
    private javax.swing.JLabel mVias1;
    // End of variables declaration//GEN-END:variables
}
